# site
# --- editar y ajustar de acuerdo al curso 
site_name: Nombre del Curso
site_description: "Sitio Web del Curso"
site_author: "Nombre Apellido"
#site_url: https://curso.unsam.edu.ar

# repository
# --- si el sitio está alojado en un repo, describirlo acá 
repo_name: 'cursos-unsam-mkdocs-template'
repo_url: https://github.com/trypanosomatics/cursos-unsam-mkdocs-template

# theme 
# --- customizar apariencia editando palette 
# --- consultar https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  logo: 'img/favicon.png'  # este logo es el que aparece al lado del nombre del curso
  favicon: img/favicon.png # este logo es el que aparece en la pestaña del chrome
  name: material
  language: es 
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tracking
    - navigation.tabs
 #   - navigation.sections
#    - navigation.tabs.sticky # --> hace que la navigation bar baje cuando se escrolea.
#    - navigation.indexes # Si se saca, cada section del index se puede ampliar INCOMPATIBLE CON toc.integrate y creo que con navigation tracking
    - toc.integrate # Integra la table of contents a la navigation
    - navigation.top
    
  palette: 
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch 
        name: Cambiar a modo oscuro
    - scheme: slate 
      primary: indigo
      accent: indigo
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro

# plugins
plugins:
  - search
  - mkdocs-video 
  - awesome-pages

  #- git-revision-date
  #- tags:
      #tags_file: tags.md # En particular no me parecieron útiles

# markdown extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - toc:
      title: Contenidos
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true


# extra
# --- editar los URLs, agregar los links especificos a cada cuenta, canal, etc. 
# --- reordenar los bloques de iconos + links de acuerdo al gusto
#extra:
#  social:
#    - icon: fontawesome/brands/slack
#      link: https://workspace-name.slack.com
#   - icon: fontawesome/brands/github
#     link: https://github.com/repo/name
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/cuenta
#    - icon: fontawesome/brands/youtube
#      link: https://youtube.com/channel/channel-id
#    - icon: fontawesome/brands/discord
#      link: https://discord.com/server

# extra++
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # Esto permite que las tablas se puedan ordenar según la columna. Lo que no vi es como hacerlo selectivo para cada tabla.
  - javascripts/tablesort.js

# Esto organiza lo que es la navegación. El nivel más alto (Inicio, Acerca de, etc) va a ser una pestaña en la barra de navegación
# No hay dropdowns pero aparece en una navigation bar al costado que se puede o no integrar con la tabla de contenidos (comentando o descomentando toc.integrate en theme --> features -toc.integrate). 
nav:
    - Inicio: 'index.md'
    - Acerca de: 'acerca.md'
    - Contenidos: 'contenidos.md'
    - Cronograma: 'cronograma.md'
    - Docentes: 'docentes.md'
    - Teoricas:
        - teoricas/inicio.md
        - Teórica 1: teoricas/1-Teorica-Uno/index.md
        - Teórica 2: teoricas/2-Teorica-Dos/index.md
        - Teórica 3: teoricas/3-Teorica-Tres/index.md
        - Resumen: teoricas/resumen.md
    - Practicos: 
        - 'practicos/inicio.md'
        - TP1: 'practicos/1-Trabajo-Practico-Uno/index.md'
        - TP2: 'practicos/2-Trabajo-Practico-Dos/index.md'
        - TP3: 'practicos/3-Trabajo-Practico-Tres/index.md'
        - Resumen: 'practicos/resumen.md'
    - Instructivos: instructivos.md

# copyright
# --- editar y ajustar de acuerdo al curso
copyright: Copyright &copy; 2022 Area Bioinformatica UNSAM  
