# site
# --- editar y ajustar de acuerdo al curso 
site_name: Herramientas Bioinformáticas para el análisis de estructura, desorden e interacciones de proteínas
site_description: "Sitio Web del Curso de Bioinformática Estructural"
#site_author: "Nombre Apellido"
site_url: https://bioinformatica-iib.github.io/estructural/

# repository
# --- si el sitio está alojado en un repo, describirlo acá 
# repo_name: 'estructural'
# repo_url: https://github.com/bioinformatica-iib/estructural

# theme 
# --- customizar apariencia editando palette 
# --- consultar https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  logo: 'img/logo-unsam-negro.png'  # este logo es el que aparece al lado del nombre del curso
  favicon: img/logo-unsam-negro.png # este logo es el que aparece en la pestaña del chrome
  name: material
  font: 
    text: Cabin
    code: Roboto Mono
  language: es 
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.tracking
    - navigation.tabs
#    - navigation.sections
#    - navigation.tabs.sticky # --> hace que la navigation bar baje cuando se escrolea.
#    - navigation.indexes # Si se saca, cada section del index se puede ampliar INCOMPATIBLE CON toc.integrate y creo que con navigation tracking
    - toc.integrate # Integra la table of contents a la navigation
    - navigation.top
    
  palette: 
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch 
        name: Cambiar a modo oscuro
    - scheme: slate 
      primary: blue
      accent: blue
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Cambiar a modo claro

# plugins
plugins:
  - search
  - mkdocs-video 
  - awesome-pages
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom

  #- git-revision-date
  #- tags:
      #tags_file: tags.md # En particular no me parecieron útiles

# markdown extensions
markdown_extensions:
  - meta
  - admonition
  - footnotes
  - attr_list
  - def_list
  - md_in_html
  - sane_lists
  - toc:
      title: Contenidos
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

# extra
# --- editar los URLs, agregar los links especificos a cada cuenta, canal, etc. 
# --- reordenar los bloques de iconos + links de acuerdo al gusto
#extra:
#  social:
#    - icon: fontawesome/brands/slack
#      link: https://workspace-name.slack.com
#   - icon: fontawesome/brands/github
#     link: https://github.com/repo/name
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/cuenta
#    - icon: fontawesome/brands/youtube
#      link: https://youtube.com/channel/channel-id
#    - icon: fontawesome/brands/discord
#      link: https://discord.com/server

# extra++
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # Esto permite que las tablas se puedan ordenar según la columna. Lo que no vi es como hacerlo selectivo para cada tabla.
  - javascripts/tablesort.js
  - javascripts/mathjax.js # Esto es para formulas matematicas
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# Esto organiza lo que es la navegación. El nivel más alto (Inicio, Acerca de, etc) va a ser una pestaña en la barra de navegación
# No hay dropdowns pero aparece en una navigation bar al costado que se puede o no integrar con la tabla de contenidos (comentando o descomentando toc.integrate en theme --> features -toc.integrate). 
nav:
    - Inicio: 'index.md'
    - Acerca de: 'acerca.md'
    - Contenidos: 'contenidos.md'
    - Cronograma: 'cronograma.md'
    - Docentes: 'docentes.md'
    - Teóricas:
        - teoricas/inicio.md
        - Teórica 1a: teoricas/teorica1a/index.md
        - Teórica 1b: teoricas/teorica1b/index.md
        - Teórica 2: teoricas/teorica2/index.md
        - Teórica 3: teoricas/teorica3/index.md
        - Teórica 4: teoricas/teorica4/index.md
        - Teórica 5: teoricas/teorica5/index.md
    #    - Teórica 6: teoricas/teorica6/index.md

    #    - Resumen: teoricas/resumen.md
    - Prácticos: 
        - 'practicos/inicio.md'
        - TP1 - Bases de Datos: 'practicos/db_uniprot/index.md'
        - TP2 - Chimera: 'practicos/chimera/index.md'
        - TP3 - Modelado por homología: 'practicos/Modelado_Por_Homologia/index.md'
        - TP4 - Modelado Parte II: 'practicos/modelado_alphafold/index.md'
        - TP5 - Interacciones Proteína-Proteína: 'practicos/ppi/index.md'
        - TP6 - Predicción de desorden y Bases de Datos: 'practicos/Regiones-flexibles/index.md'
        - TP7 - Motivos Lineales - Parte I: 'practicos/motivosRegEx/index.md'
        # - TP8 - TP8. Motivos Lineales - Parte II: 'practicos/Motivos_Lineales/index.md'
        # - TP9 - TP9. Trabajo Práctico Integrador: 'practicos/integrador/index.md'
    #    - Resumen: 'practicos/resumen.md'
    #- Instructivos: instructivos.md

# copyright
# --- editar y ajustar de acuerdo al curso
copyright: Copyright &copy; 2024 Area Bioinformática UNSAM  
